#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES. Usage: scripts/set-release-secrets.sh [sparkle|apple|check]
#   sparkle  run on the OFFICE Mac (holds the Sparkle EdDSA key)
#   apple    run on the PERSONAL Mac, in a GUI Terminal (not SSH)
#   check    just list the secrets
# ──────────────────────────────────────────────────────────────────────────

export GH_REPO="Ashishjain608/write-better"   # gh honours this, same as -R
TEAM_ID="ZC7J54L64J"
EXPECTED_PUB="X4auol1WgUT/mKvw1iHkYZcQq8uIBbhsgZE3c4taur0="
ALL_SECRETS=(APPLE_CERTIFICATE APPLE_CERTIFICATE_PASSWORD APPLE_SIGNING_IDENTITY
             APPLE_ID APPLE_PASSWORD APPLE_TEAM_ID SPARKLE_ED_PRIVATE_KEY)

# Secrets never touch the repo: everything temporary lives here and is removed on exit.
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
ENV_FILE="$WORK/.env"   # ask/ask_secret read defaults from here; keep it empty

command -v gh >/dev/null || { echo "gh is not installed" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not logged in: run 'gh auth login'" >&2; exit 1; }

MODE="${1:-}"
if [[ -z "$MODE" ]]; then
  printf '\n  Which part?\n    1) sparkle  (office Mac)\n    2) apple    (personal Mac, GUI Terminal)\n    3) check    (list secrets)\n  Choice: '
  read -r c || true
  case "$c" in 1) MODE=sparkle;; 2) MODE=apple;; *) MODE=check;; esac
fi

list_stage() {
  stage "Check the secrets on GitHub"
  local listed missing=()
  listed=$(gh secret list --json name -q '.[].name') || { warn "gh secret list failed"; return 1; }
  for n in "${ALL_SECRETS[@]}"; do
    if grep -qx "$n" <<<"$listed"; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$n"
    else printf '  %s✗%s %s\n' "$RED" "$RESET" "$n"; missing+=("$n"); fi
  done
  if (( ${#missing[@]} )); then
    warn "missing ${#missing[@]}: ${missing[*]}"
    SKIPPED+=("missing secrets: ${missing[*]} (run the other part of this script)")
  else
    say "All 7 release secrets are set."
  fi
}

case "$MODE" in
sparkle)
  TOTAL_STAGES=2
  banner "WriteBetter release secrets: Sparkle key (office Mac)"

  stage "Export the Sparkle EdDSA key"
  GK=$(find build/DerivedData/SourcePackages/artifacts/sparkle -name generate_keys -type f 2>/dev/null | head -1 || true)
  [[ -x "${GK:-}" ]] || GK=$(find "$(dirname "$0")/../build" -name generate_keys -type f 2>/dev/null | head -1 || true)
  [[ -x "${GK:-}" ]] || { warn "generate_keys not found; build the app once so SwiftPM fetches Sparkle"; exit 1; }
  say "Using $GK"
  say "macOS may ask to let generate_keys use the keychain item: click Always Allow."
  pub=$("$GK" -p) || { warn "generate_keys -p failed"; exit 1; }
  if [[ "$pub" != "$EXPECTED_PUB" ]]; then
    warn "keychain public key ($pub) != Info.plist key ($EXPECTED_PUB). Wrong Mac or key; stopping."
    exit 1
  fi
  say "Keychain public key matches Info.plist."
  "$GK" -x "$WORK/sparkle.key" >/dev/null
  [[ -s "$WORK/sparkle.key" ]] || { warn "export produced an empty file"; exit 1; }
  SPARKLE_KEY=$(cat "$WORK/sparkle.key")
  rm -f "$WORK/sparkle.key"
  set_secret SPARKLE_ED_PRIVATE_KEY "$SPARKLE_KEY"
  pause "Next: check the list."

  list_stage
  ;;

apple)
  TOTAL_STAGES=5
  banner "WriteBetter release secrets: Apple signing (personal Mac)"

  stage "Find the signing identity"
  if [[ -n "${SSH_CONNECTION:-}" ]]; then
    warn "You're in an SSH session; the keychain is locked here. Run this from Terminal.app on the Mac itself."
    confirm "Continue anyway?" || exit 1
  fi
  say "Developer ID identities in your keychain:"
  security find-identity -v -p codesigning | grep -i 'Developer ID Application' || warn "none found: wrong Mac?"
  step "Copy the quoted name, e.g. Developer ID Application: Ashish Jain (ZC7J54L64J)"
  ask IDENT "Paste the name (no quotes):"
  [[ "$IDENT" == "Developer ID Application:"*"($TEAM_ID)" ]] || { warn "expected 'Developer ID Application: ... ($TEAM_ID)'"; exit 1; }

  stage "Export the certificate as .p12"
  printf '%s' "$WORK" | pbcopy 2>/dev/null || true
  open -a "Keychain Access" || true
  step "Keychain Access > login > My Certificates > right-click the Developer ID Application cert"
  step "Export... > format Personal Information Exchange (.p12)"
  step "In the save dialog press Cmd-Shift-G, paste (already on your clipboard): $WORK"
  step "Name it cert.p12, Save, and choose an export password (you'll type it below)"
  note "The folder is temporary and is deleted when this wizard exits."
  pause "Press Enter once cert.p12 is saved."
  [[ -s "$WORK/cert.p12" ]] || { warn "$WORK/cert.p12 not found"; exit 1; }
  ask_secret P12_PASS "Type the same export password:"
  [[ -n "$P12_PASS" ]] || { warn "empty password"; exit 1; }
  export P12_PASS
  # Soft check: old LibreSSL may not read new .p12 ciphers, so only warn.
  if command -v openssl >/dev/null && ! openssl pkcs12 -in "$WORK/cert.p12" -passin env:P12_PASS -noout >/dev/null 2>&1; then
    warn "openssl couldn't open the .p12 (wrong password, or just an old openssl)."
    confirm "Continue anyway?" || exit 1
  fi
  CERT_B64=$(base64 -i "$WORK/cert.p12" | tr -d '\n')
  rm -f "$WORK/cert.p12"

  stage "Apple ID for notarization"
  open_url "https://account.apple.com/account/manage"
  step "Sign-In and Security > App-Specific Passwords > create one named 'write-better-ci'"
  ask APPLE_ID_VAL "Apple ID email:"
  ask_secret APPLE_PW "App-specific password (xxxx-xxxx-xxxx-xxxx):"
  [[ -n "$APPLE_ID_VAL" && -n "$APPLE_PW" ]] || { warn "both are required"; exit 1; }

  stage "Set the six Apple secrets"
  set_secret APPLE_CERTIFICATE "$CERT_B64"
  set_secret APPLE_CERTIFICATE_PASSWORD "$P12_PASS"
  set_secret APPLE_SIGNING_IDENTITY "$IDENT"
  set_secret APPLE_ID "$APPLE_ID_VAL"
  set_secret APPLE_PASSWORD "$APPLE_PW"
  set_secret APPLE_TEAM_ID "$TEAM_ID"
  pause "Next: check the list."
  list_stage
  ;;

*)
  TOTAL_STAGES=1
  list_stage
  ;;
esac

finish
